/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.DAOPerfil;
import javax.swing.JOptionPane;
import modelos.Perfil;

/**
 *
 * @author JHON JAIRO CORTES
 */
public class PerfilCrear extends javax.swing.JInternalFrame {

    /**
     * Creates new form PerfilCrear
     */
    public PerfilCrear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabeceraCrearP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCuerpoCrearP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cajaNomPerfil = new javax.swing.JTextField();
        panelBotonesCrearP = new javax.swing.JPanel();
        btnCrearPerfil = new javax.swing.JButton();
        btnCancelarPerfil = new javax.swing.JButton();

        setClosable(true);
        setTitle("PERFILES CREAR");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(559, 384));

        panelCabeceraCrearP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CREACIÓN DE PERFILES");

        javax.swing.GroupLayout panelCabeceraCrearPLayout = new javax.swing.GroupLayout(panelCabeceraCrearP);
        panelCabeceraCrearP.setLayout(panelCabeceraCrearPLayout);
        panelCabeceraCrearPLayout.setHorizontalGroup(
            panelCabeceraCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraCrearPLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        panelCabeceraCrearPLayout.setVerticalGroup(
            panelCabeceraCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraCrearPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCuerpoCrearP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre del perfil: ");

        javax.swing.GroupLayout panelCuerpoCrearPLayout = new javax.swing.GroupLayout(panelCuerpoCrearP);
        panelCuerpoCrearP.setLayout(panelCuerpoCrearPLayout);
        panelCuerpoCrearPLayout.setHorizontalGroup(
            panelCuerpoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoCrearPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cajaNomPerfil)
                .addContainerGap())
        );
        panelCuerpoCrearPLayout.setVerticalGroup(
            panelCuerpoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoCrearPLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(panelCuerpoCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaNomPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        panelBotonesCrearP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCrearPerfil.setText("CREAR");
        btnCrearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPerfilActionPerformed(evt);
            }
        });

        btnCancelarPerfil.setText("CANCELAR");
        btnCancelarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesCrearPLayout = new javax.swing.GroupLayout(panelBotonesCrearP);
        panelBotonesCrearP.setLayout(panelBotonesCrearPLayout);
        panelBotonesCrearPLayout.setHorizontalGroup(
            panelBotonesCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesCrearPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrearPerfil)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarPerfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotonesCrearPLayout.setVerticalGroup(
            panelBotonesCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesCrearPLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelBotonesCrearPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearPerfil)
                    .addComponent(btnCancelarPerfil))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCuerpoCrearP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCabeceraCrearP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotonesCrearP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCabeceraCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCuerpoCrearP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonesCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPerfilActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarPerfilActionPerformed

    private void crearPerfil() {
        String cajaNombrePerfil = cajaNomPerfil.getText();

        if (cajaNombrePerfil.isEmpty()) {
            JOptionPane.showMessageDialog(panelCuerpoCrearP, "Debe escribir el nombre del perfil.");
        } else {
            DAOPerfil objDao = new DAOPerfil();
            Perfil objPerfil = new Perfil();
            
            objPerfil.setNombrePerfil(cajaNombrePerfil);
            
            if(objDao.agregar(objPerfil)){
                cajaNomPerfil.setText("");
                JOptionPane.showMessageDialog(panelCuerpoCrearP, "Registro agregado correctamente.");
            }else{
                JOptionPane.showMessageDialog(panelCuerpoCrearP, "No se puede crear el registro.");
            }
            cajaNomPerfil.requestFocus();
        }
    }

    private void btnCrearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPerfilActionPerformed
        crearPerfil();
    }//GEN-LAST:event_btnCrearPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPerfil;
    private javax.swing.JButton btnCrearPerfil;
    private javax.swing.JTextField cajaNomPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelBotonesCrearP;
    private javax.swing.JPanel panelCabeceraCrearP;
    private javax.swing.JPanel panelCuerpoCrearP;
    // End of variables declaration//GEN-END:variables
}
