/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JInternalFrame;

/**
 *
 * @author JHON JAIRO CORTES
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        panelTablero = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuPerfiles = new javax.swing.JMenu();
        jMenuItemCrearP = new javax.swing.JMenuItem();
        jMenuItemListarP = new javax.swing.JMenuItem();
        jMenuItemAdminP = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemCrearU = new javax.swing.JMenuItem();
        jMenuItemListarU = new javax.swing.JMenuItem();
        jMenuItemAdminU = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROYECTO FINAL");
        setResizable(false);

        panelTablero.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jMenuArchivo.setText("Archivo");

        jMenuItemAcercaDe.setText("Acerca De");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAcercaDe);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuPerfiles.setText("Perfiles");

        jMenuItemCrearP.setText("Crear");
        jMenuItemCrearP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearPActionPerformed(evt);
            }
        });
        jMenuPerfiles.add(jMenuItemCrearP);

        jMenuItemListarP.setText("Listar");
        jMenuItemListarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarPActionPerformed(evt);
            }
        });
        jMenuPerfiles.add(jMenuItemListarP);

        jMenuItemAdminP.setText("Administrar");
        jMenuItemAdminP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdminPActionPerformed(evt);
            }
        });
        jMenuPerfiles.add(jMenuItemAdminP);

        jMenuBar1.add(jMenuPerfiles);

        jMenuUsuarios.setText("Usuarios");

        jMenuItemCrearU.setText("Crear");
        jMenuItemCrearU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearUActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemCrearU);

        jMenuItemListarU.setText("Listar");
        jMenuItemListarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarUActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemListarU);

        jMenuItemAdminU.setText("Administrar");
        jMenuItemAdminU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdminUActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemAdminU);

        jMenuBar1.add(jMenuUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarVentanaPanel(JInternalFrame ventana){
        if(panelTablero.getComponentCount() > 0){
            panelTablero.removeAll();
        }
        panelTablero.add(ventana);
    }
    
    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemAdminPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdminPActionPerformed
        //**********************************************************************
        //definicion de variables
        //**********************************************************************
        PerfilAdministrar ventanaPerfilAdmin;
        //**********************************************************************
        //**********************************************************************
        //creacion de objetos
        //**********************************************************************
        ventanaPerfilAdmin = new PerfilAdministrar();
        //**********************************************************************
        agregarVentanaPanel(ventanaPerfilAdmin);
        ventanaPerfilAdmin.show();
    }//GEN-LAST:event_jMenuItemAdminPActionPerformed

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        //**********************************************************************
        //definicion de variables
        //**********************************************************************
        AcercaDe ventanaAcercaDe;
        //**********************************************************************
        //**********************************************************************
        //creacion de objetos
        //**********************************************************************
        ventanaAcercaDe = new AcercaDe();
        //**********************************************************************
        agregarVentanaPanel(ventanaAcercaDe);
        ventanaAcercaDe.show();
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void jMenuItemCrearPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearPActionPerformed
        //**********************************************************************
        //definicion de variables
        //**********************************************************************
        PerfilCrear ventanaPerfilCrear;
        //**********************************************************************
        //**********************************************************************
        //creacion de objetos
        //**********************************************************************
        ventanaPerfilCrear = new PerfilCrear();
        //**********************************************************************
        agregarVentanaPanel(ventanaPerfilCrear);
        ventanaPerfilCrear.show();
    }//GEN-LAST:event_jMenuItemCrearPActionPerformed

    private void jMenuItemListarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarPActionPerformed
        //**********************************************************************
        //definicion de variables
        //**********************************************************************
        PerfilesListar ventanaPerfilListar;
        //**********************************************************************
        //**********************************************************************
        //creacion de objetos
        //**********************************************************************
        ventanaPerfilListar = new PerfilesListar();
        //**********************************************************************
        agregarVentanaPanel(ventanaPerfilListar);
        ventanaPerfilListar.show();
    }//GEN-LAST:event_jMenuItemListarPActionPerformed

    private void jMenuItemCrearUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearUActionPerformed
        //**********************************************************************
        //definicion de variables
        //**********************************************************************
        UsuarioCrear ventanaUsuarioCrear;
        //**********************************************************************
        //**********************************************************************
        //creacion de objetos
        //**********************************************************************
        ventanaUsuarioCrear = new UsuarioCrear();
        //**********************************************************************
        agregarVentanaPanel(ventanaUsuarioCrear);
        ventanaUsuarioCrear.show();
    }//GEN-LAST:event_jMenuItemCrearUActionPerformed

    private void jMenuItemListarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarUActionPerformed
        //**********************************************************************
        //definicion de variables
        //**********************************************************************
        UsuarioListar ventanaUsuarioListar;
        //**********************************************************************
        //**********************************************************************
        //creacion de objetos
        //**********************************************************************
        ventanaUsuarioListar = new UsuarioListar();
        //**********************************************************************
        agregarVentanaPanel(ventanaUsuarioListar);
        ventanaUsuarioListar.show();
    }//GEN-LAST:event_jMenuItemListarUActionPerformed

    private void jMenuItemAdminUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdminUActionPerformed
        //**********************************************************************
        //definicion de variables
        //**********************************************************************
        UsuarioAdministrar ventanaUsuarioAdmin;
        //**********************************************************************
        //**********************************************************************
        //creacion de objetos
        //**********************************************************************
        ventanaUsuarioAdmin = new UsuarioAdministrar();
        //**********************************************************************
        agregarVentanaPanel(ventanaUsuarioAdmin);
        ventanaUsuarioAdmin.show();
    }//GEN-LAST:event_jMenuItemAdminUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemAdminP;
    private javax.swing.JMenuItem jMenuItemAdminU;
    private javax.swing.JMenuItem jMenuItemCrearP;
    private javax.swing.JMenuItem jMenuItemCrearU;
    private javax.swing.JMenuItem jMenuItemListarP;
    private javax.swing.JMenuItem jMenuItemListarU;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuPerfiles;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables
}
